import { Router } from 'express';
import auth from './auth.routes.js';
import tenants from './tenant.routes.js';
import users from './user.routes.js';
import categories from './category.routes.js';
import products from './product.routes.js';
import suppliers from './supplier.routes.js';
import customers from './customer.routes.js';
import purchases from './purchase.routes.js';
import sales from './sale.routes.js';
import saleReturns from './saleReturn.routes.js';
import purchaseReturns from './purchaseReturn.routes.js';
import inventory from './inventory.routes.js';
import reports from './report.routes.js';
import ledgers from './ledger.routes.js';
import misc from './misc.routes.js';

const router = Router();
router.use('/auth', auth);
router.use('/tenants', tenants);
router.use('/users', users);
router.use('/categories', categories);
router.use('/products', products);
router.use('/suppliers', suppliers);
router.use('/customers', customers);
router.use('/purchases', purchases);
router.use('/sales', sales);
router.use('/sale-returns', saleReturns);
router.use('/purchase-returns', purchaseReturns);
router.use('/inventory', inventory);
router.use('/reports', reports);
router.use('/ledgers', ledgers);
router.use('/', misc);
export default router;
